FROM node:14-alpine AS frontend

WORKDIR /app

COPY src/main/resources/images /app/images
COPY src/main/resources/js /app/js
COPY src/main/resources/html /app/html
COPY src/main/resources/css /app/css

RUN npm install -g http-server

EXPOSE 8081

CMD ["http-server", ".", "-p", "8081"]
