version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - network

  uncaught-heroes-service-discovery:
    build:
      context: .
      dockerfile: uncaught-heroes-backend/uncaught-heroes-service-discovery/Dockerfile
    container_name: uncaught-heroes-service-discovery
    ports:
      - "8761:8761"
      - "5007:5007"
      - "12347:12347"
    volumes:
      - ./jrebel:/opt/jrebel
    networks:
      - network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 10

  uncaught-heroes-main:
    build:
      context: .
      dockerfile: uncaught-heroes-backend/uncaught-heroes-main/Dockerfile
    container_name: uncaught-heroes-main
    depends_on:
      mongodb:
        condition: service_started
      uncaught-heroes-service-discovery:
        condition: service_healthy
    ports:
      - "5005:5005"
      - "8080:8080"
      - "12345:12345"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/uncaught-heroes
    volumes:
      - ./jrebel:/opt/jrebel
    networks:
      - network

  uncaught-heroes-api-gateway:
    build:
      context: .
      dockerfile: uncaught-heroes-backend/uncaught-heroes-api-gateway/Dockerfile
    container_name: uncaught-heroes-api-gateway
    depends_on:
      - uncaught-heroes-main
    ports:
      - "8765:8765"
      - "5006:5006"
      - "12346:12346"
    volumes:
      - ./jrebel:/opt/jrebel
    networks:
      - network

  uncaught-heroes-frontend:
    build:
      context: .
      dockerfile: uncaught-heroes-frontend/Dockerfile
    container_name: uncaught-heroes-frontend
    depends_on: 
      - uncaught-heroes-main
    ports:
      - "8081:8081"
    networks:
      - network

volumes:
  mongodb_data:

networks:
  network:
    name: network