FROM maven:3-openjdk-17

WORKDIR /app

COPY pom.xml .
COPY src/ ./src/

EXPOSE 5005
EXPOSE 8080
EXPOSE 12345

ENV REBEL_HOME="/opt/jrebel"
ENV JAVA_OPTS="-agentpath:$REBEL_HOME/lib/libjrebel64.so -Drebel.remoting_plugin=true -Drebel.remoting_port=12345 $JAVA_OPTS"

RUN mvn package

CMD ["sh", "-c", "java $JAVA_OPTS -jar target/uncaughtHeroes.jar"]
