version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  uncaught-heroes-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uncaught-heroes-backend
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/uncaught-heroes

volumes:
  mongodb_data:
