version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  uncaught-heroes-backend:
    build:
      context: uncaught-heroes-backend
      dockerfile: Dockerfile-backend
    container_name: uncaught-heroes-backend
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
      - "12345:12345"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/uncaught-heroes
    volumes:
      - ./jrebel:/opt/jrebel

  uncaught-heroes-frontend:
    build:
      context: uncaught-heroes-frontend
      dockerfile: Dockerfile-frontend
    container_name: uncaught-heroes-frontend
    ports:
      - "8081:8081"

volumes:
  mongodb_data: