FROM node:14-alpine AS frontend

WORKDIR /app

COPY app/images /app/images
COPY app/js /app/js
COPY app/html /app/html
COPY app/css /app/css

RUN npm install -g http-server

EXPOSE 8081

CMD ["http-server", ".", "-p", "8081"]
